name: Add comment
on:
  pull_request_target:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'ok-to-test'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          body: |
            /test ci/centos/k8s-e2e-external-storage/1.22
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          body: |
            /test ci/centos/k8s-e2e-external-storage/1.23
